<a href="https://colab.research.google.com/github/riioaditya/data-maning/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [152]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [153]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [154]:
print(x)

[['Netherlands' 25.0 48695]
 ['Poland' 33.0 48950]
 ['Poland' 31.0 54500]
 ['United Kingdom' 38.0 61800]
 ['Netherlands' nan 15600]
 ['Netherlands' 35.0 58000]
 ['Poland' nan 42150]
 ['United Kingdom' 48.0 80000]
 ['Denmark' 50.0 30800]
 ['Denmark' 37.0 60000]]


In [155]:
print(y)

['Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes']


In [156]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[: , 1:3])

In [157]:
print(x)

[['Netherlands' 25.0 48695.0]
 ['Poland' 33.0 48950.0]
 ['Poland' 31.0 54500.0]
 ['United Kingdom' 38.0 61800.0]
 ['Netherlands' 37.125 15600.0]
 ['Netherlands' 35.0 58000.0]
 ['Poland' 37.125 42150.0]
 ['United Kingdom' 48.0 80000.0]
 ['Denmark' 50.0 30800.0]
 ['Denmark' 37.0 60000.0]]


In [158]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [159]:
print(x)

[[0.0 1.0 0.0 0.0 25.0 48695.0]
 [0.0 0.0 1.0 0.0 33.0 48950.0]
 [0.0 0.0 1.0 0.0 31.0 54500.0]
 [0.0 0.0 0.0 1.0 38.0 61800.0]
 [0.0 1.0 0.0 0.0 37.125 15600.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 0.0 37.125 42150.0]
 [0.0 0.0 0.0 1.0 48.0 80000.0]
 [1.0 0.0 0.0 0.0 50.0 30800.0]
 [1.0 0.0 0.0 0.0 37.0 60000.0]]


In [160]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [161]:
print(y)

[1 1 0 1 0 0 0 0 0 1]


In [162]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [163]:
print(x_train)

[[0.0 0.0 1.0 0.0 37.125 42150.0]
 [0.0 1.0 0.0 0.0 37.125 15600.0]
 [0.0 1.0 0.0 0.0 25.0 48695.0]
 [0.0 0.0 0.0 1.0 38.0 61800.0]
 [0.0 0.0 1.0 0.0 33.0 48950.0]
 [0.0 0.0 0.0 1.0 48.0 80000.0]
 [1.0 0.0 0.0 0.0 50.0 30800.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [164]:
print(x_test)

[[0.0 0.0 1.0 0.0 31.0 54500.0]
 [1.0 0.0 0.0 0.0 37.0 60000.0]]


In [165]:
print(y_train)

[0 0 1 1 1 0 0 0]


In [166]:
print(y_test)

[0 1]


In [167]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [168]:
print(x_train)

[[0.0 0.0 1.0 0.0 -0.10434525713440435 -0.33230648468078755]
 [0.0 1.0 0.0 0.0 -0.10434525713440435 -1.778805046955596]
 [0.0 1.0 0.0 0.0 -1.7237836478603596 0.024278565793360133]
 [0.0 0.0 0.0 1.0 0.01252143085612852 0.7382658975677995]
 [0.0 0.0 1.0 0.0 -0.6552882148040593 0.038171489837807444]
 [0.0 0.0 0.0 1.0 1.348140722176504 1.7298392999558037]
 [1.0 0.0 0.0 0.0 1.6152645804405792 -0.9506778097963836]
 [0.0 1.0 0.0 0.0 -0.38816435653998416 0.5312340882779963]]


In [169]:
print(x_test)

[[0.0 0.0 1.0 0.0 -0.9224120730681343 0.3405468955110725]
 [1.0 0.0 0.0 0.0 -0.12104049827590903 0.6401981984305243]]
